version: '3.9'

services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Adminproduits@2024
      POSTGRES_DB: produits
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist database data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
  postgres-data:  # Define a volume to persist database data
